
fn vscope_err() int !err {
    throw err
}
fn vscope_err2() (int, int) !err {
    throw err
}

test "Value scopes" {

    let a = <{
        return 1
    }
    let b = vscope_err() ? <{
        return 2
    }
    let c = vscope_err() ? <{
        if true {
            return 3
        }
        return 4
    }

    assert(a == 1)
    assert(b == 2)
    assert(c == 3)

    let d, e = <{
        if true {
            return 1,2
        }
        return 3,4
    }

    assert(d == 1)
    assert(e == 2)

    // let f, g = vscope_err2() ? <{
    //     return 3,4
    // }

    // assert(f == 1)
    // assert(g == 2)
}
